apiVersion: v1
kind: Service
metadata:
  name: b3-api-service
  annotations:
    cloud.google.com/app-protocols: '{"my-https-port":"HTTPS","my-http-port":"HTTP"}'
spec:
  selector:
    app: b3-api
  type: NodePort
  ports:
    - name: my-http-port
      protocol: TCP
      port: 80
      targetPort: 4000
    - name: my-https-port
      port: 443
      targetPort: 4000