apiVersion: v1
kind: Service
metadata:
  name: b3-api-service
spec:
  selector:
    app: b3-api
  type: LoadBalancer
  loadBalancerIP: 34.105.26.64
  ports:
    - name: http
      protocol: TCP
      port: 4000
      targetPort: 4000