apiVersion: apps/v1
kind: Deployment
metadata:
  name: b3-api-pod

spec:
  containers:
    - name: b3-api-containers
      image: us-west1-docker.pkg.dev/projeto-estudos-344512/b3-api-repository/b3-api
      