apiVersion: v1
kind: Service
metadata:
  name: b3-api-service
spec:
  selector:
    app: b3-api
  type: LoadBalancer
  loadBalancerIP:	35.223.229.146  #só funciona com IP estático zonal, não pode ser glogal
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 4000