apiVersion: v1
kind: Service
metadata:
  name: b3-api-service
spec:
  selector:
    app: b3-api
  type: LoadBalancer
  loadBalancerIP:	34.160.136.103 
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 4000