const codAcaoEnum = Object.freeze({
        ARZZ3 : 'AREZZO CO ON NM',
        B3SA3 : 'B3 ON',
        BBAS3 : 'BANCO DO BRASIL',
        BPAC11 : 'BTGP BANCO UNT',
        CASH3 : 'MELIUZ ON NM',
        CPFE3 : 'CPFL ENERGIA',
        CSMG3 : 'COPASA MG',
        CSNA3 : 'CSN',
        ELET3 : 'ELETROBRÁS',
        FHER3 : 'FER HERINGER',
        HAPV3 : 'HAPVIDA ',
        HBOR3 : 'HELBOR',
        KLBN3 : 'KLABIN 3',
        KLBN4 : 'KLABIN 4',
        LAND3 : 'TERRASANTAPA',
        LUPA3 : 'LUPATECH',
        MOVI3 : 'MOVIDA',
        OIBR3 : 'OI',
        PRIO3 : 'PETRORIO',
        RAPT4 : 'RANDON S.A.',
        RCSL4 : 'RECRUSUL',
        RPMG3 : 'REFINARIA DE PETRÓLEOS DE MANGUINHOS',
        SLCE3 : 'SLC AGRICOLA',
        TEND3 : 'TENDA',
        TGMA3 : 'TEGMA',
        TOTS3 : 'TOTVS',
        TRIS3 : 'TRISUL',
        VBBR3 : 'VIBRA',
        VIVT3 : 'TELEF BRASIL',
        WEGE3 : 'WEG SA'
});

module.exports = codAcaoEnum;